apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: g8aj2xjve-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-fd4b9b8a19.zthc.p3.openshiftapps.com/rhtap/rhtap-qe-python:5c22ccb6888afdad122df31d25d87582e6c40cf9@sha256:f17dec2a8cb4626e3655d2f59573f8d558661a9bf8ba8356d152332ef415c4a0
          name: container-image
